{{- if .Values.ingress.enabled -}}
{{- $fullName := include "test-api.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "test-api.fullname" . }}-{{ .Values.environment.stage }}
  labels:
    app: {{ template "test-api.name" . }}
    chart: {{ template "test-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- if .Values.ingress.whitelist.ranges -}}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.ingress.whitelist.ranges }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostName }}
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ template "test-api.fullname" . }}-{{ .Values.environment.stage }}
              port:
                name: http
  tls: 
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
        - {{ .Values.ingress.hostName }}
{{- end }}